### ISSUE TITLE
why is "elevate.exe" present in the windows installation?

### ISSUE THREAD

**Issue by aylsal-3295** [drata/drata-agent#3]
I deleted it and drata agent still works and it still gets the info. 
elevate.exe seems to be a very old and untrustworthy executable.

**Comment by mnrdrata** [comment]
Thank you for the feedback, @aylsal-3295. This is indeed part of the Electron nsis target. We will review the possibility of excluding it in a future release. It is not required for the Drata Agent to operate.

Please note that the `elevate.exe` included with an official Drata distribution is signed with the Drata code signing certificate.

**Comment by mnrdrata** [comment]
Removed elevate.exe from distribution package in 3.5.0.

**Comment by aylsal-3295** [comment]
awesome! thanks
