### ISSUE TITLE
Is gatekeeper really an anti-virus?

### ISSUE THREAD

**Issue by pleberre** [drata/drata-agent#4]
Hi,

I see that the Drata agent check for "anti-virus" on OS X is to check if gatekeeper is active. This seems a bit odd as gatekeeper will not scan files, for instance for infected office document, etc. Is there any specific official ground to classify "gatekeeper" as anti-virus?

Thanks,

Philippe

**Comment by mnrdrata** [comment]
Thanks, @pleberre. The Drata Agent only collects data from devices. The compliance assessments are performed by Drata servers based on that data and account specific settings.

The relevant data sent for malware protection assessment on MacOS are the xprotect settings [here](https://github.com/drata/drata-agent/blob/main/src/main/services/system-query/macos-system-query.service.ts#L113). For more information see Apple's documentation https://support.apple.com/guide/security/protecting-against-malware-sec469d47bd8/web.

For the fastest response or more information regarding your account, please contact Drata support.
