### ISSUE TITLE
OS version supported?

### ISSUE THREAD

**Issue by lpgauth** [drata/drata-agent#7]
Hi,
Could you please list in the README which OS/Versions are supported? Which Linux distribution is supported?

Thanks,
LP

**Comment by lpgauth** [comment]
Looking at the code, if the OS is supported by `osquery` it should work no? I have an employee running Debian and I'd prefer not to have him switch distros.

**Comment by mnrdrata** [comment]
It's possible for the application to run on other debian-based distros, assuming all dependencies are compatible. However, Drata can only provide support on the specific distros and versions tested.
